# Generated by Django 5.1.6 on 2025-03-01 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_certificate_chaireview_store'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certificate',
            new_name='ChaiCertificate',
        ),
    ]
