# Generated by Django 5.1.6 on 2025-03-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0004_rename_certificate_chaicertificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaireview',
            old_name='cahi',
            new_name='chai',
        ),
    ]
