# Generated by Django 5.1.6 on 2025-03-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0005_rename_cahi_chaireview_chai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaireview',
            old_name='COMMENT',
            new_name='comment',
        ),
    ]
